server:
  port: 8080

spring:
  application:
    name: bookmarker
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/bkmk
    username: hu 
    password: root1234 
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

  # jpa:
  #   hibernate:
  #     ddl-auto: update # JPA 설정 (자동으로 스키마 업데이트)
  #   show-sql: true # 실행되는 SQL을 콘솔에 출력

logging:
  level:
    org.springframework: INFO # Spring 관련 로그 레벨 설정

naver:
  clientId: SzgEN9VXSOHN5bk3CsNP
  clientPw: _071veCjxt
  apiUrl: https://openapi.naver.com/v1/search/book.json