server:
  port: 8080

spring:
  application:
    name: bookmarker
  datasource:
    url: jdbc:mysql://localhost:3306/bkmk # 데이터베이스 URL 설정
    username: hu 
    password: root1234 
    driver-class-name: com.mysql.cj.jdbc.Driver # JDBC 드라이버 설정1
  # jpa:
  #   hibernate:
  #     ddl-auto: update # JPA 설정 (자동으로 스키마 업데이트)
  #   show-sql: true # 실행되는 SQL을 콘솔에 출력

logging:
  level:
    org.springframework: INFO # Spring 관련 로그 레벨 설정
